eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
spring:
 application:
    name: newz-nexflix-zuul-api-gateway
server:
  port: 8091 

zuul:
  routes:
    authenticationservice:
      serviceId: authentication-service
    newsservice:
      serviceId: news-service
    newssourceservice:
      serviceId: newssource-service
    userprofileservice:
      serviceId: userprofile-service