spring:
  application:
    name: news-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    mongodb:
      #      for hobbes and gitlab ci please uncomment the username and password
      #      username: ${MONGO_USER}
      #      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE:news_service_db}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
     
server:
 port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka