# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: "3.7"

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql_container
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - my-db:/var/lib/mysql

  mongodb:
    image: mongo:4.4.2-bionic
    container_name: mongo_container
    network_mode: host
    volumes:
      - my-db:/var/lib/mongodb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

  authenticationservice:
    image: supreethnewzapp/authenticationservice:v0.4
    container_name: authenticationservice
    network_mode: host
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: authentication_service_db
    depends_on:
      - mysql
    restart: always

  newsservice:
    image: supreethnewzapp/newsservice:v0.3
    container_name: newsservice
    network_mode: host
    ports:
      - 8081:8081
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: news_service_db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    restart: always

  newssourceservice:
    image: supreethnewzapp/newssourceservice:v0.3
    container_name: newssourceservice
    network_mode: host
    ports:
      - 8083:8083
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: newssource_service_db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    restart: always

  userprofileservice:
    image: supreethnewzapp/userprofileservice:v0.3
    container_name: userprofileservice
    network_mode: host
    ports:
      - 8084:8084
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: userprofile_service_db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    restart: always

  eurekaserver:
    image: supreethnewzapp/eurekaserverservice:v0.3
    container_name: eurekaserver
    network_mode: host
    ports:
      - 8761:8761

  zuul:
    image: supreethnewzapp/zuulservice:v0.3
    container_name: zuulservice
    network_mode: host
    ports:
      - 8091:8091
volumes:
  my-db: