spring:
  application:
    name: news-service
  data:
    mongodb:
      #      for hobbes and gitlab ci please uncomment the username and password
      #      username: ${MONGO_USER}
      #      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE:news_service_db}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true