# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: "3.7"

services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin

  mongodb:
    image: mongo:4.4.2-bionic
    container_name: mongo_container

  authenticationservice:
    image: supreethnewzapp/authenticationservice:v0.1
    container_name: authenticationservice
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: authentication_service_db
    depends_on:
      - mysql
    restart: always

  newsservice:
    image: supreethnewzapp/newsservice:v0.1
    container_name: newsservice
    ports:
      - 8081:8081
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: news_service_db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    restart: always

  newssourceservice:
    image: supreethnewzapp/newssourceservice:v0.1
    container_name: newssourceservice
    ports:
      - 8083:8083
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: newssource_service_db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    restart: always

  userprofileservice:
    image: supreethnewzapp/userprofileservice:v0.1
    container_name: userprofileservice
    ports:
      - 8084:8084
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: userprofile_service_db
      MONGO_PORT: 27017
    depends_on:
      - mongodb
    restart: always